### GET všichni uživatelé
GET http://localhost:8080/api/users

### POST nový uživatel
POST http://localhost:8080/api/users/registerStudent
Content-Type: application/json

{
  "jmeno": "Kveta",
  "prijmeni": "Nováková",
  "email": "Kveta.novakova@osu.cz",
  "studijniCislo": "P121256",
  "heslo": "Heslo123",
  "role": "STUDENT"
}
