create table users (
                       id bigint generated by default as identity primary key,
                       first_name varchar(255),
                       last_name varchar(255),
                       email varchar(255) not null unique,
                       password varchar(255),
                       student_number varchar(255) unique,
                       company_name varchar(255),
                       role varchar(50),
                       last_login timestamp,
                       active boolean,
                       agreed_to_terms boolean
);

create table verification_token (
                                    id bigint generated by default as identity primary key,
                                    token varchar(255),
                                    user_id bigint,
                                    expiry_date timestamp,
                                    purpose varchar(50) not null,
                                    constraint fk_verification_user foreign key (user_id) references users(id)
);

create table practices (
                           id bigint generated by default as identity primary key,
                           name varchar(255),
                           description varchar(255),
                           valid_from timestamp,
                           valid_to timestamp,
                           founder_id bigint,
                           student_id bigint,
                           constraint fk_practices_founder foreign key (founder_id) references users(id),
                           constraint fk_practices_student foreign key (student_id) references users(id)
);

create table attachments (
                             id bigint generated by default as identity primary key,
                             file_data bytea,
                             file_size bigint,
                             file_type varchar(255),
                             title varchar(255),
                             url varchar(255),
                             practice_detail_id bigint,
                             task_id bigint,
                             uploaded_by bigint
);

create table refresh_token (
                               id bigint generated by default as identity primary key,
                               token varchar(255) not null unique,
                               user_id bigint not null,
                               expiry_date timestamp not null,
                               revoked boolean not null,
                               constraint fk_refresh_token_user foreign key (user_id) references users(id)
);
